# Generated by Django 2.2.5 on 2019-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
