# Generated by Django 2.2.3 on 2019-08-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20190201_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
