# Generated by Django 2.2.5 on 2019-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.IntegerField(choices=[(0, 'Close'), (1, 'Private'), (2, 'Public')], default=2),
        ),
    ]
