# Generated by Django 2.2.5 on 2019-09-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='cover',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='image',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
