# Generated by Django 2.2.5 on 2019-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20190904_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.IntegerField(choices=[(0, 'Close'), (1, 'Private'), (2, 'Public')], default=2),
        ),
    ]
