# Generated by Django 2.2.5 on 2019-11-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_party_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partycategory',
            name='image',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
