# Generated by Django 3.0 on 2019-12-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_partycategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.IntegerField(choices=[(1, 'Close'), (2, 'Private'), (3, 'Public')], default=3),
        ),
    ]
