# Generated by Django 3.0 on 2020-01-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_auto_20191229_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.IntegerField(choices=[(1, 'Close'), (2, 'Private'), (3, 'Public')], db_index=True, default=3),
        ),
    ]
