# Generated by Django 2.1.3 on 2019-01-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
