# Generated by Django 2.1.3 on 2018-12-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songparty',
            options={'verbose_name_plural': 'Song parties'},
        ),
    ]
