# Generated by Django 2.1.3 on 2018-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20181204_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songparty',
            name='key',
            field=models.SlugField(max_length=16, unique=True),
        ),
    ]
