# Generated by Django 2.1.3 on 2019-01-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20181204_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songparty',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='song',
            name='player',
            field=models.IntegerField(choices=[(0, 'YouTube'), (1, 'SoundCloud')], default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party'),
        ),
        migrations.DeleteModel(
            name='SongParty',
        ),
    ]
