# Generated by Django 2.2.5 on 2019-09-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_party_status'),
        ('song', '0003_song_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_category', to='party.PartyCategory')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_category', to='song.Song')),
            ],
            options={
                'verbose_name_plural': 'Song categories',
                'ordering': ('id',),
                'unique_together': {('song', 'category')},
            },
        ),
    ]
