# Generated by Django 3.0 on 2019-12-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20190908_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='player',
            field=models.IntegerField(choices=[(1, 'Youtube'), (2, 'Soundcloud')], default=1),
        ),
    ]
